image: node:9

before_script:
  - yarn install

stages:
  - test

mocha:
  stage: test
  cache:
    paths:
      - node_modules
  script:
    - npm run test

typescript:
  stage: test
  cache:
    paths:
      - node_modules
  script:
    - npm run typescript

lint:
  stage: test
  cache:
    paths:
      - node_modules
  script:
    - npm run lint

jsdoc:
  stage: test
  cache:
    paths:
      - node_modules
  script:
    - npm run jsdoc